Repository Path-Check/covid-safe-paths, pull requests merged in 2020-03, with the labels that each got.

#43 Tweaking the Import functionality
  app/helpers/GoogleData.js
Labels: For next release, Work In Progress

#121 Update exportscreen.json
  app/locales/it/exportscreen.json
Labels: help wanted, translation

#122 Update import.json
  app/locales/it/import.json
Labels: help wanted, translation

#123 Update intro.json
  app/locales/it/intro.json
Labels: help wanted, translation

#124 Update locationTracking.json
  app/locales/it/locationTracking.json
Labels: help wanted, translation

#142 Added a three-dot menu button and licenses page to the main screen (LocationTracking.js)
  .prettierrc.js
  App.js
  app/Entry.js
  app/assets/images/kebabIcon.png
  app/locales/en/index.js
  app/locales/en/licensesscreen.json
  app/views/Licenses.js
  app/views/LocationTracking.js
  dev_setup.sh
  package.json
  yarn.lock
Labels: enhancement

#154 Add support for 'Marathi' locale
  app/locales/en/intro.json
  app/locales/languages.js
  app/locales/mr/exportscreen.json
  app/locales/mr/import.json
  app/locales/mr/index.js
  app/locales/mr/intro.json
  app/locales/mr/locationTracking.json
Labels: help wanted, translation

#125 Translated pt locations files
  app/locales/pt/exportscreen.json
  app/locales/pt/import.json
  app/locales/pt/intro.json
  app/locales/pt/locationTracking.json
Labels: help wanted, translation

#210 Add code formatting rules with git-hooks
  .prettierignore
  .prettierrc.js
  app/Entry.js
  app/helpers/GoogleData.js
  app/helpers/GoogleTakeOutAutoImport.js
  app/locales/languages.js
  app/services/BroadcastingService.js
  app/services/LocationService.js
  app/views/Import.js
  app/views/LocationTracking.js
  app/views/News.js
  app/views/Overlap.js
  app/views/Welcome.js
  package-lock.json
  package.json
Labels: devprod

#229 Brazilian Portuguese language support
  app/locales/languages.js
  app/locales/pt_BR/exportscreen.json
  app/locales/pt_BR/import.json
  app/locales/pt_BR/index.js
  app/locales/pt_BR/intro.json
  app/locales/pt_BR/licensesscreen.json
  app/locales/pt_BR/locationTracking.json
  app/locales/pt_BR/overlap.json
Labels: translation

#259 Update Overlap screen to update when it comes into focus
  app/views/Overlap.js
  jestSetupFile.js
Labels: enhancement

#215 FR locale (translation)
  app/locales/fr/exportscreen.json
  app/locales/fr/import.json
  app/locales/fr/index.js
  app/locales/fr/intro.json
  app/locales/fr/licensesscreen.json
  app/locales/fr/locationTracking.json
  app/locales/fr/notification.json
  app/locales/fr/overlap.json
Labels: translation

#276 Adding Kannada Language support
  app/locales/kn/exportscreen.json
  app/locales/kn/import.json
  app/locales/kn/index.js
  app/locales/kn/intro.json
  app/locales/kn/licensesscreen.json
  app/locales/kn/locationTracking.json
  app/locales/kn/notification.json
  app/locales/kn/overlap.json
  app/locales/languages.js
Labels: translation

#283 Export fix for iOS
  app/views/Export.js
Labels: For next release

#279 Android Bluetooth Contact Tracing V1.
  app/services/BroadcastingService.js
  package.json
Labels: For next release

#213 CS (Czech) locale
  app/locales/cs/exportscreen.json
  app/locales/cs/import.json
  app/locales/cs/index.js
  app/locales/cs/intro.json
  app/locales/cs/licensesscreen.json
  app/locales/cs/locationTracking.json
  app/locales/cs/notification.json
  app/locales/cs/overlap.json
  app/locales/languages.js
Labels: help wanted, translation

#258 added new language support for the urdu
  app/locales/languages.js
  app/locales/ur/exportscreen.json
  app/locales/ur/import.json
  app/locales/ur/index.js
  app/locales/ur/intro.json
  app/locales/ur/licensesscreen.json
  app/locales/ur/locationTracking.json
  app/locales/ur/notification.json
  app/locales/ur/overlap.json
Labels: translation
