Repository Path-Check/covid-safe-paths, pull requests merged in 2020-05, with the labels that each got.

#724 Remove rebasing from suggestions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: devprod, question

#521 iOS: Added local notification in terminate function.
  ios/COVIDSafePaths/AppDelegate.m
  ios/en.lproj/Localizable.strings
Labels: Enhancement, ios, question

#694 Build time feature flags (Phase 1)
  .env
  .env.beta
  .env.release
  .github/workflows/create-release.yml
  App.js
  __mocks__/react-native-config.js
  android/app/build.gradle
  android/app/proguard-rules.pro
  app/components/Feature.js
  app/components/__tests__/Feature.spec.js
  app/components/__tests__/__snapshots__/Feature.spec.js.snap
  app/helpers/flags.js
  app/views/Settings.js
  app/views/__tests__/Settings.spec.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: devprod

#710 Load raw html eulas, and upload changes to Lokalise automatically
  .github/workflows/build.yml
  .github/workflows/i18n.yml
  .groovylintrc.json
  android/app/build.gradle
  android/app/src/main/java/org/pathcheck/covidsafepaths/MainActivity.java
  android/settings.gradle
  app/components/EulaModal.js
  app/locales/check.sh
  app/locales/eula/en.html
  app/locales/eula/en_html.js
  app/locales/eula/ht.html
  app/locales/eula/ht_html.js
  app/locales/push.sh
  metro.config.js
  package.json
  yarn.lock
Labels: translation

#823 [1.0.x master] Legal page updates (#815)
  app/assets/LICENSE.json
  app/locales/en.json
  app/locales/ht.json
  app/views/Licenses.js
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
Labels: High Priority

#825 [1.0.x master] Bug/fix android crash permissions
  app/services/LocationService.js
Labels: High Priority

#822 [1.0.x master] About page copy changes (#805)
  app/locales/en.json
  app/locales/ht.json
  app/views/About.js
Labels: High Priority
