Repository Path-Check/covid-safe-paths, pull requests merged in 2020-06, with the labels that each got.

#931 wip
  app/components/Option/OptionSelect.js
  app/components/Typography.js
  app/views/assessment/AssessmentButton.js
  app/views/assessment/AssessmentQuestion.js
  app/views/assessment/AssessmentStart.js
  app/views/assessment/constants.js
  app/views/assessment/endScreens/AssessmentEnd.js
  app/views/assessment/endScreens/AssessmentEndCaregiver.js
  app/views/assessment/endScreens/AssessmentEndComplete.js
  app/views/assessment/endScreens/AssessmentEndDistancing.js
  app/views/assessment/endScreens/AssessmentEndEmergency.js
  app/views/assessment/endScreens/AssessmentEndIsolate.js
  app/views/assessment/endScreens/AssessmentEndShare.js
Labels: Do Not Merge (yet)

#969 Exposure Notifications Debug Menu iOS
  app/Entry.js
  app/components/NavigationBarWrapper.tsx
  app/exposureNotificationsNativeModule.ts
  app/views/Settings/ENDebugMenu.js
  app/views/Settings/ENLocalDiagnosisKeyScreen.tsx
  app/views/Settings/Section.js
  app/views/Settings/index.js
  app/views/__tests__/Settings.spec.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  ios/BTE/API/APIClient.swift
  ios/BTE/API/Model/ExposureKey.swift
  ios/BTE/API/Requests/DiagnosisKeyRequests.swift
  ios/BTE/API/Requests/ExposureConfigurationRequests.swift
  ios/BTE/ExposureManager.swift
  ios/BTE/Extensions/ENTemporaryExposureKey+Extensions.swift
  ios/BTE/Storage/BTESecureStorage.swift
  ios/BTE/bridge/DebugMenuModule.m
  ios/COVIDSafePaths.xcodeproj/project.pbxproj
  ios/COVIDSafePathsTests/RealmSecureStorageTest.swift
  ios/Common/SafePathsSecureStorage.swift
  ios/GPS/storage/GPSSecureStorage.swift
  ios/GPS/storage/SecureStorage.swift
  ios/Podfile
  ios/Podfile.lock
Labels: Work In Progress

#1105 Upcase navHeader text
  app/styles/typography.ts
  app/views/__tests__/__snapshots__/FeatureFlagToggles.spec.js.snap
  app/views/__tests__/__snapshots__/Import.spec.js.snap
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
Labels: UI/UX

#1111 Fix unused style import
  app/views/onboarding/OnboardingPermissions.js
Labels: Bug
