Repository Path-Check/covid-safe-paths, pull requests merged in 2020-04, with the labels that each got.

#318 fixed syntax error in gj labels block on dev, languages.js
  app/locales/languages.js
Labels: Bug, For next release

#342 Reworking the UI for exposure notifications
  app/constants/colors.js
  app/locales/en/notification.json
  app/views/LocationTracking.js
  app/views/Notification.js
Labels: For next release

#329 Make some hardcoded texts translatable
  app/locales/en/index.js
  app/locales/en/licensesscreen.json
  app/locales/en/locationService.json
  app/services/LocationService.js
  app/views/Licenses.js
  app/views/LocationTracking.js
Labels: For next release, High Priority

#247 android import fix #114
  app/views/Import.js
Labels: Do Not Merge (yet), High Priority, question

#366 Start of news from Healthcare Authorities
  app/assets/svgs/permissionUnknown.js
  app/locales/en/english.json
  app/views/LocationTracking.js
  app/views/News.js
  app/views/Settings.js
  package.json
  yarn.lock
Labels: For next release

#367 Add locale picker, Haitian Creole translation
  app/components/NativePicker.js
  app/locales/ht/exportscreen.json
  app/locales/ht/haitian.json
  app/locales/ht/import.json
  app/locales/ht/index.js
  app/locales/ht/intro.json
  app/locales/ht/licensesscreen.json
  app/locales/ht/locationTracking.json
  app/locales/ht/overlap.json
  app/locales/languages.js
  app/views/onboarding/Onboarding1.js
Labels: For next release

#240 Enforce Yarn, remove package-lock.json and add Jest testing to pre-commit hooks
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: devprod

#414 Changes based on Mayo feedback
  app/assets/LICENSE.json
  app/assets/images/foreArrow.png
  app/assets/images/kebabIcon.png
  app/assets/images/privatekit.png
  app/assets/svgs/stateAtRisk.js
  app/locales/en/english.json
  app/views/Licenses.js
  app/views/LocationTracking.js
  app/views/News.js
  app/views/Notification.js
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
  app/views/__tests__/__snapshots__/News.spec.js.snap
Labels: For next release

#417 iOS splash screen update
  app/assets/fonts/IBMPlexMono-Bold.ttf
  app/assets/fonts/IBMPlexMono-BoldItalic.ttf
  app/assets/fonts/IBMPlexMono-ExtraLight.ttf
  app/assets/fonts/IBMPlexMono-ExtraLightItalic.ttf
  app/assets/fonts/IBMPlexMono-Italic.ttf
  app/assets/fonts/IBMPlexMono-Light.ttf
  app/assets/fonts/IBMPlexMono-LightItalic.ttf
  app/assets/fonts/IBMPlexMono-Medium.ttf
  app/assets/fonts/IBMPlexMono-MediumItalic.ttf
  app/assets/fonts/IBMPlexMono-Regular.ttf
  app/assets/fonts/IBMPlexMono-SemiBold.ttf
  app/assets/fonts/IBMPlexMono-SemiBoldItalic.ttf
  app/assets/fonts/IBMPlexMono-Thin.ttf
  app/assets/fonts/IBMPlexMono-ThinItalic.ttf
  ios/PrivateKit/Base.lproj/LaunchScreen.xib
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Contents.json
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Home screen.png
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Home screen@2x.png
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Home screen@3x.png
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Rectangle.png
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Rectangle@2x.png
  ios/PrivateKit/Images.xcassets/bgImage.imageset/Rectangle@3x.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/Contents.json
  ios/PrivateKit/Images.xcassets/logoImage.imageset/PrivateKitLogo.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/PrivateKitLogo@2x.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/PrivateKitLogo@3x.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/logo.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/logo@2x.png
  ios/PrivateKit/Images.xcassets/logoImage.imageset/logo@3x.png
Labels: ios

#427 Fix i18n string extraction tool bug
  package.json
  yarn.lock
Labels: devprod, translation

#441 Italian_Translation_Andy_Nuzzo
  app/locales/it.json
  app/locales/languages.js
  i18next-parser.config.js
Labels: translation

#480 Auto sort import statements with Prettier
  App.js
  app/Entry.js
  app/Util.js
  app/components/Button.js
  app/components/ButtonWrapper.js
  app/components/NativePicker.js
  app/components/NavigationBarWrapper.js
  app/helpers/GoogleData.js
  app/helpers/GoogleTakeOutAutoImport.js
  app/helpers/Intersect.js
  app/helpers/authorities.js
  app/helpers/convertPointsToString.js
  app/locales/languages.js
  app/services/BackgroundTaskService.js
  app/services/BroadcastingService.js
  app/services/LocationService.js
  app/views/About.js
  app/views/ChooseProvider.js
  app/views/Export.js
  app/views/Import.js
  app/views/Licenses.js
  app/views/LocationTracking.js
  app/views/MapLocation.js
  app/views/News.js
  app/views/Notification.js
  app/views/Overlap.js
  app/views/Settings.js
  app/views/__tests__/Overlap.spec.js
  app/views/__tests__/__snapshots__/Overlap.spec.js.snap
  app/views/onboarding/Onboarding1.js
  app/views/onboarding/Onboarding2.js
  app/views/onboarding/Onboarding3.js
  app/views/onboarding/Onboarding4.js
  app/views/onboarding/Onboarding5.js
  index.js
  package.json
  yarn.lock
Labels: devprod

#491 Spanish Translation Miquel Vila Porte
  app/locales/es.json
  app/locales/languages.js
  i18next-parser.config.js
Labels: translation

#499 Remove hardcoded link to Haitian health authority
  app/constants/storage.js
  app/helpers/Intersect.js
  app/locales/en.json
  app/views/ChooseProvider.js
  app/views/News.js
  app/views/__tests__/__snapshots__/News.spec.js.snap
Labels: For next release, High Priority

#498 Safe paths italian fix based on issue #483
  app/locales/it.json
Labels: Do Not Merge (yet), translation

#493 Feature/cn-language
  app/locales/languages.js
  app/locales/zh-Hant.json
  i18next-parser.config.js
Labels: translation

#479 Russian Translation by Ksenia Lukacher
  app/locales/languages.js
  app/locales/ru.json
  i18next-parser.config.js
Labels: translation

#490 Add French translation
  app/locales/fr.json
  app/locales/languages.js
  i18next-parser.config.js
Labels: translation

#504 [RC] fix function call
  app/services/BackgroundTaskService.js
Labels: For next release

#508 [RC] Notification fix
  app/views/LocationTracking.js
Labels: For next release

#467 Event history UX update
  .prettierignore
  app/Entry.js
  app/Util.js
  app/components/NavigationBarWrapper.js
  app/components/Typography.js
  app/components/__tests__/Typography.spec.js
  app/components/__tests__/__snapshots__/Typography.spec.js.snap
  app/constants/__tests__/Theme.spec.js
  app/constants/__tests__/__snapshots__/Theme.spec.js.snap
  app/constants/colors.js
  app/constants/history.js
  app/constants/themes.js
  app/locales/all-dayjs-locales.js
  app/locales/en.json
  app/locales/languages.js
  app/views/ExposureHistory/CalendarDay.js
  app/views/ExposureHistory/DataCircle.js
  app/views/ExposureHistory/DetailedHistory.js
  app/views/ExposureHistory/ExposureCalendarView.js
  app/views/ExposureHistory/ExposureHistory.js
  app/views/ExposureHistory/MonthGrid.js
  app/views/ExposureHistory/SingleExposureDetail.js
  app/views/ExposureHistory/__tests__/CalendarDay.spec.js
  app/views/ExposureHistory/__tests__/DataCircle.spec.js
  app/views/ExposureHistory/__tests__/ExposureHistory.spec.js
  app/views/ExposureHistory/__tests__/MonthGrid.spec.js
  app/views/ExposureHistory/__tests__/SingleExposureDetails.spec.js
  app/views/ExposureHistory/__tests__/__snapshots__/CalendarDay.spec.js.snap
  app/views/ExposureHistory/__tests__/__snapshots__/DataCircle.spec.js.snap
  app/views/ExposureHistory/__tests__/__snapshots__/MonthGrid.spec.js.snap
  app/views/ExposureHistory/__tests__/__snapshots__/SingleExposureDetails.spec.js.snap
  app/views/LocationTracking.js
  app/views/Notification.js
  app/views/Settings.js
  app/views/__tests__/Overlap.spec.js
  app/views/__tests__/__snapshots__/Import.spec.js.snap
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
  app/views/__tests__/__snapshots__/News.spec.js.snap
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  jestSetupFile.js
  package.json
  yarn.lock
Labels: For next release, High Priority

#502 Update Haitian translation
  app/locales/ht.json
Labels: For next release, High Priority, translation

#519 Add Language translation for Indonesian
  app/locales/id.json
  app/locales/languages.js
  i18next-parser.config.js
Labels: translation

#524 Safe paths Vietnamese translation
  app/locales/languages.js
  app/locales/vi.json
  i18next-parser.config.js
Labels: High Priority, translation

#530 Haitian for the rc build
  app/locales/ht.json
  app/locales/languages.js
Labels: Do Not Merge (yet)

#531 Feature/language malayalam
  app/locales/languages.js
  app/locales/ml.json
Labels: translation

#537 Slovak_Translation_Aneta_Laukova
  app/locales/languages.js
  app/locales/sk.json
  i18next-parser.config.js
Labels: translation

#525 Safe paths haitian update
  app/locales/ht.json
Labels: High Priority, translation

#552 Issue #548 - Inconsistent language usage of COVID19 and COVID-19
  app/locales/en.json
  app/locales/id.json
  app/locales/ml.json
  app/locales/vi.json
Labels: translation

#551 SafePaths Slovak_New_Keys_Addition_Aneta
  app/locales/sk.json
Labels: translation

#556 Allow VS Code to type hint `jest` global
  jsconfig.json
  package.json
  yarn.lock
Labels: devprod

#560 Update android splash text to "Safe Paths"
  android/app/src/main/res/drawable/ic_splash_logo_text.xml
Labels: High Priority

#545 Romanian Translation
  app/locales/languages.js
  app/locales/ro.json
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  i18next-parser.config.js
Labels: translation

#567 Get detox in workflows
  .eslintrc.js
  .eslintrc.json
  .github/workflows/test.yml
  .gitignore
  android/app/build.gradle
  android/app/src/androidTest/org/pathcheck/covidsafepaths/DetoxTest.java
  android/build.gradle
  android/gradle.properties
  app/components/Button.js
  app/views/ChooseProvider.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  e2e/InsufficientLocationPermissions.spec.js
  e2e/NoLocationPermissions.spec.js
  e2e/NoNotificationsPermissions.spec.js
  e2e/Onboarding.spec.js
  e2e/Permissions.spec.js
  e2e/config.json
  e2e/helpers/onboarding.js
  e2e/init.js
  e2e/pages/EnableLocation.po.js
  e2e/pages/FinishSetup.po.js
  e2e/pages/Onboarding1.po.js
  e2e/pages/Onboarding2.po.js
  e2e/pages/Onboarding3.po.js
  e2e/pages/Onboarding4.po.js
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Do Not Merge (yet), ios

#529 Fix intersect to handle multiple authorities
  app/constants/history.js
  app/helpers/Intersect.js
  app/helpers/__tests__/Intersect.spec.js
  app/views/ExposureHistory/ExposureHistory.js
  app/views/ExposureHistory/__tests__/ExposureHistory.spec.js
Labels: High Priority

#410 (Fix) Improve Google Location Data import Experience, fix import logic
  __mocks__/react-native-document-picker.js
  app/helpers/General.js
  app/helpers/GoogleData.js
  app/helpers/GoogleTakeOutAutoImport.js
  app/helpers/tests/GoogleData.spec.js
  app/helpers/tests/GoogleTakeOutAutoImport.spec.js
  app/helpers/tests/GoogleTakeoutUtils.js
  app/helpers/tests/__mocks__/General.js
  app/helpers/tests/fixtures/googleImport.js
  app/locales/en.json
  app/views/Import.js
  app/views/__tests__/Import.spec.js
  app/views/__tests__/__snapshots__/Import.spec.js.snap
  e2e/pages/FinishSetup.po.js
  e2e/pages/Onboarding1.po.js
  e2e/pages/Onboarding2.po.js
  e2e/pages/Onboarding3.po.js
  e2e/pages/Onboarding4.po.js
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: High Priority

#573 Feature/polish
  app/helpers/GoogleTakeOutAutoImport.js
  app/helpers/__tests__/Intersect.spec.js
  app/helpers/tests/GoogleTakeOutAutoImport.spec.js
  app/locales/languages.js
  app/locales/pl.json
  app/views/Import.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  i18next-parser.config.js
Labels: translation

#651 Disable google import on release builds
  app/views/Settings.js
Labels: High Priority

#655 Lokalise: Translations update (ht)
  app/locales/ht.json
Labels: High Priority, translation

#628 Fix languages specific for history page
  app/views/ExposureHistory/ExposureCalendarView.js
Labels: question

#626 Feature/ita update
  app/locales/it.json
Labels: translation

#614 Translation to Brazilian Portuguese
  app/locales/languages.js
  app/locales/pt_BR.json
  i18next-parser.config.js
Labels: translation

#642 [i18n] Don't translate terms_of_use_url
  app/Entry.js
  app/locales/ar.json
  app/locales/en.json
  app/views/Licenses.js
  app/views/__tests__/Licenses.spec.js
  app/views/__tests__/__snapshots__/Licenses.spec.js.snap
Labels: translation

#678 Clean up most of remaining eslint issues
  .eslintrc.js
  __mocks__/react-native-i18n.js
  app/components/ButtonWrapper.js
  app/components/NativePicker.js
  app/helpers/__tests__/Intersect.spec.js
  app/helpers/tests/__mocks__/General.js
  app/services/BroadcastingService.js
  app/services/__tests__/LocationService.spec.js
  app/views/About.js
  app/views/Import.js
  app/views/News.js
  app/views/__tests__/LocationTracking.spec.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  jest/setupFile.js
  package.json
Labels: devprod

#587 Auto add authorities
  __mocks__/react-native-push-notification.js
  app/Entry.js
  app/constants/storage.js
  app/helpers/General.js
  app/helpers/Intersect.js
  app/locales/en.json
  app/services/BackgroundTaskService.js
  app/services/HCAService.js
  app/services/LocationService.js
  app/services/__mocks__/mockHCA.js
  app/services/__mocks__/mockUserLocHistory.js
  app/services/__tests__/HCAService.spec.js
  app/views/ChooseProvider.js
  app/views/LocationTracking.js
  app/views/__tests__/__snapshots__/Settings.spec.js.snap
  app/views/onboarding/Onboarding5.js
  e2e/helpers/language.js
  e2e/helpers/onboarding.js
  e2e/onboarding/InsufficientLocationPermissions.spec.js
  e2e/onboarding/NoAuthSubscriptionPermission.spec.js
  e2e/onboarding/NoLocationPermissions.spec.js
  e2e/onboarding/NoNotificationsPermissions.spec.js
  e2e/onboarding/Onboarding.spec.js
  e2e/onboarding/Permissions.spec.js
  e2e/onboarding/UnsignedEula.spec.js
  e2e/pages/EnableAuthoritySubscription.po.js
  e2e/pages/EnableLocation.po.js
  e2e/pages/EnableNotifications.po.js
  e2e/pages/FinishSetup.po.js
  e2e/pages/Onboarding5.po.js
Labels: Do Not Merge (yet)

#648 Fix incorrect "plural" keys, add key checks for new PRs
  .github/workflows/i18n.yml
  app/components/NativePicker.js
  app/locales/check.sh
  app/locales/en.json
  app/views/Export.js
  app/views/Import.js
  app/views/Settings.js
  app/views/Settings/GoogleMapsImport.js
  app/views/__tests__/__snapshots__/Export.spec.js.snap
  app/views/__tests__/__snapshots__/Import.spec.js.snap
  i18next-parser.config.js
  package.json
Labels: translation

#709 Fix count placeholder for authorities translation
  app/locales/en.json
Labels: translation
