Repository Path-Check/covid-safe-paths, pull requests merged in 2020-07, with the labels that each got.

#1150 Refactor self assessment screens
  app/components/Typography.tsx
  app/locales/en.json
  app/styles/colors.ts
  app/styles/typography.ts
  app/views/assessment/Agreement.js
  app/views/assessment/AssessmentQuestion.js
  app/views/assessment/AssessmentStart.js
  app/views/assessment/Button.js
  app/views/assessment/Context.js
  app/views/assessment/EmergencyAssessment.js
  app/views/assessment/Info.js
  app/views/assessment/__tests__/Button.spec.js
  app/views/assessment/__tests__/Info.spec.js
  app/views/assessment/__tests__/__snapshots__/Button.spec.js.snap
  app/views/assessment/__tests__/__snapshots__/Info.spec.js.snap
  app/views/assessment/__tests__/__snapshots__/Question.spec.js.snap
  app/views/assessment/__tests__/__snapshots__/Start.spec.js.snap
  app/views/assessment/__tests__/endScreens/Caregiver.spec.js
  app/views/assessment/__tests__/endScreens/Complete.spec.js
  app/views/assessment/__tests__/endScreens/Distancing.spec.js
  app/views/assessment/__tests__/endScreens/Emergency.spec.js
  app/views/assessment/__tests__/endScreens/Isolate.spec.js
  app/views/assessment/__tests__/endScreens/Share.spec.js
  app/views/assessment/__tests__/endScreens/__snapshots__/Caregiver.spec.js.snap
  app/views/assessment/__tests__/endScreens/__snapshots__/Complete.spec.js.snap
  app/views/assessment/__tests__/endScreens/__snapshots__/Distancing.spec.js.snap
  app/views/assessment/__tests__/endScreens/__snapshots__/Emergency.spec.js.snap
  app/views/assessment/__tests__/endScreens/__snapshots__/Isolate.spec.js.snap
  app/views/assessment/__tests__/endScreens/__snapshots__/Share.spec.js.snap
  app/views/assessment/components/Button.js
  app/views/assessment/components/InfoText.js
  app/views/assessment/endScreens/AssessmentComplete.js
  app/views/assessment/endScreens/Caregiver.js
  app/views/assessment/endScreens/Distancing.js
  app/views/assessment/endScreens/Emergency.js
  app/views/assessment/endScreens/Isolate.js
  app/views/assessment/endScreens/Share.js
  app/views/assessment/index.js
  app/views/assessment/survey.en.json
Labels: Enhancement

#1168 Import test location data
  app/Entry.js
  app/api/import/importLocationsApi.ts
  app/locales/en.json
  app/navigation/index.ts
  app/views/Import.js
  app/views/Settings/ImportFromUrl.tsx
  app/views/__tests__/__snapshots__/Import.spec.js.snap
Labels: Enhancement

#1204 Implement next steps screen redesign
  app/assets/svgs/export.ts
  app/constants/authorities.ts
  app/locales/en.json
  app/styles/typography.ts
  app/views/ExposureHistory/NextSteps.tsx
Labels: Enhancement

#1202 Show Alert to User When Enabling EN for App if EN is not Authorized by the OS
  app/bt/Home/Home.spec.tsx
  app/bt/Home/Home.tsx
  app/locales/en.json
Labels: Do Not Merge (yet), Work In Progress

#1254 re-added hashes to exported file
  app/gps/Export/ExportLocally.js
Labels: Enhancement

#1188 Dayjs localization updates
  app/helpers/locales/es-pr.js
  app/helpers/locales/ht.js
  app/locales/all-dayjs-locales.js
  app/locales/languages.js
Labels: Enhancement

#1291 [SAF-821] Fix feature flag language reset
  app/locales/languages.ts
  app/views/FeatureFlagToggles.js
Labels: Enhancement

#1297 App breaking on code input for HA screen fix
  app/Entry.js
  app/gps/Export/ExportStart.js
  app/views/Settings/index.tsx
Labels: Enhancement

#1306 [SAF-825] Fix exposure notification display
  app/views/ExposureHistory/History.tsx
Labels: Enhancement

#1203 [SAF-665] Delete location history option
  app/locales/en.json
  app/views/Settings/index.tsx
Labels: Enhancement

#1313 [SAF-822] Fix HA code input
  app/gps/Export/ExportCodeInput.js
Labels: Enhancement

#1317 [SAF-787] white status bar bug on android fix
  app/views/main/ServiceOffScreens/Base.tsx
Labels: Enhancement

#1319 [SAF-793] fix android ff click sound
  app/views/About.js
Labels: Enhancement

#1331 [SAF-851] Update import location data hashes
  app/api/import/importLocationsApi.ts
Labels: Bug

#1315 Bump dayjs version
  app/helpers/locales/es-pr.js
  app/helpers/locales/ht.js
  app/locales/all-dayjs-locales.js
  package.json
  yarn.lock
Labels: dependencies
